- name: Configure webservers with nginx
  hosts: all_hosts
  become: True
  tasks:
    - name: install nginx
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - nginx
    
    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/nginx.conf
    
    - name: copy index.html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: 0644

    - name: restart nginx
      service:
        name: nginx
        state: restarted
