---
- name: Configure webserver with nginx and tls
  hosts: all_hosts
  become: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/nginx.conf
    server_name: localhost

  tasks:
    - name: install nginx
      yum:
        name: nginx
        state: present
    
    - name: create directories for ssl certificates
      file:
        path: /etc/nginx/ssl
        state: directory
    
    - name: copy TLS key
      copy:
        src: files/nginx.key
        dest: {{ key_file }}
        owner: root
        mode: 0600
      notify: restart nginx
    
    - name: copy TLS certificate
      copy:
        src: files/nginx.crt
        dest: {{ cert_file }}
      notify: restart nginx

    - name: copy nginx config file
      template:
        src: templates/nginx.conf.j2
        dest: {{ conf_file }}
      notify: restart nginx
    
    - name: copy index.html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: 0644
    
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted